name: Container Build
on:
  push:
    branches: [main]
permissions:
  contents: read
  id-token: write
jobs:
  build:
    uses: terzo241-platform/platform-workflows/.github/workflows/container-build.yml@main
    with:
      image-name: 'my-test-service'
      gcp-project-id: ${{ vars.GCP_PROJECT_ID }}
      wif-provider: ${{ vars.WIF_PROVIDER }}
      wif-service-account: ${{ vars.WIF_SERVICE_ACCOUNT }}
      push: true
